name: AuthMigration

on:
  pull_request:
    branches: [master]
    types: [labeled]
  release:
    types: [published]

env:
  PRODUCTION_API: ${{ secrets.PRODUCTION_AUTH_MIGRATION_API }}
  PRODUCTION_TOKEN: ${{ secrets.PRODUCTION_DIRTY_HACK_TOKEN }}
  STAGING_API: ${{ secrets.STAGING_AUTH_MIGRATION_API }}
  STAGING_TOKEN: ${{ secrets.STAGING_DIRTY_HACK_TOKEN }}

jobs:
  adding-auth-data-in-identity-service:
    name: Adding Auth Data in Identity Service
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'release' || github.event.label.name == 'Ok to deploy in staging'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: curl
        uses: wei/curl@v1
        if: github.event_name == 'release'
        with:
          args: --location --request GET 'https://ucapi.vnksrvc.com/users/find_zone.json?location=23.750074,90.375948'
        if: github.event_name == 'pull_request'
        with:
          args: --location --request GET 'https://ucapi.vnksrvc.com/users/find_zone.json?location=23.750074,90.375948'


          # if: github.event_name == 'release'
          # args: -X POST '${{ env.PRODUCTION_API }}' --header 'Authorization: ${{ env.PRODUCTION_TOKEN }}' --form 'json_file=@"migrations.json"'

          # if: github.event_name == 'pull_request'
          # args: -X POST '${{ env.STAGING_API }}' --header 'Authorization: ${{ env.STAGING_TOKEN }}' --form 'json_file=@"migrations.json"'
